### ISSUE TITLE
Yiff-dl stops working unexpectedly.

### ISSUE THREAD

**Issue by AnonFapper69** [M-rcus/yiff-dl#16] opened 2020-10-01 21:21 UTC
I'm trying to download content from this page [here](https://yiff.party/patreon/143690) and a few posts later, the script stops working suddenly. I get the same result for some of the creators i have ripped (another example [here](https://yiff.party/patreon/127384)). Can you look into the issue and fix it? Thank you.

![Yiff-dl Issue](https://user-images.githubusercontent.com/72230411/94864406-8a7f2980-0401-11eb-8137-f4931c9a0b31.png)

**Comment by M-rcus** [comment] 2020-10-02 15:30
I'll investigate once Yiff.party comes back up.

**Comment by M-rcus** [comment] 2020-10-03 20:47
Alright, I tested with both of the creators you linked and I could not reproduce the same result.

Granted it took _a while_ to download the second profile you linked, all my downloads eventually completed (with a few exceptions where I got a [504 Gateway Timeout](https://httpstatuses.com/504) error from Yiff). There were a few downloads that temporarily stopped for a few seconds, but they eventually continued without massive issues.

Overall rips of both profiles succeeded without any major issues.

There's a chance it's a Windows issue for some reason, but I wouldn't know what.  
I did my tests with Linux (Debian 9) & Node.js v12.16.1.

Since I can't reproduce this issue, I'll be closing it, unless there's more information tied to it that shows it's an issue with the software.

**Closed by M-rcus** 2020-10-03 20:47 UTC
